name: docker-build

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghrc
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to ghrc
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/callummance/mako:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
